Update StbHardware.py
22:42:02.4078   File "/usr/lib/enigma2/python/Tools/StbHardware.py", line 8, in <module>
22:42:02.4079 ImportError: cannot import name 'BoxInfo' from partially initialized module 'Components.SystemInfo' (most likely due to a circular import) (/usr/lib/enigma2/python/Components/SystemInfo.pyc)