"[ChannelSelection]" fix crash :
TypeError: ChannelSelection.bouquetParentalControlCallback() got an unexpected keyword argument 'forceRestart'

Because of this commit -> openatv/enigma2@408d548